apiVersion: ENC[AES256_GCM,data:+zU=,iv:zsg6X2zNHxEuvRFEliieHP/OCjWVmFePgSN++x0O4tI=,tag:JrH7LE0do7bpM+6p0PthbA==,type:str]
kind: ENC[AES256_GCM,data:/I5zhBay,iv:+zIzCVHyCPpaTbLRoklN5+S5VBC1uKhOk5814JEmtr8=,tag:974HC4kiwMFcUIxTCWsW+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DkSIMCkJM2QVzGmj,iv:87zhE+qTVhlGysCXoF+BiVSZqGi4lilqUB9xyLvJv6s=,tag:Zk/8mZklJI52547e/2uLRw==,type:str]
    namespace: ENC[AES256_GCM,data:W3pMK3hhwueJ0g==,iv:7cN16w65s4NI+aYK0N/N/egbFJJv0mt9v1CzBbgB8gI=,tag:5NaI25F02WPRgYsM410MWg==,type:str]
type: ENC[AES256_GCM,data:lUZRi+R7,iv:kcLJrQJRCNNB5JE1V4KX5IZjUk5CUcCFYmbaDNmA4l0=,tag:ycAI3frnn7JtCe+QbT4DMA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:kaJ9Yi3mHXPHvT8uB9ibOPzB18a1XWY8CpippxX2Q7II2cdMJEY5byrQf2kh45yVNFh2+L8H0t/wdP3clhuaueCRTogAgAExFU3AwVfI7EFn/+s6y4pZ7s4z/L1F0nVElinxNCrMy6XeGpi4kmv8PhhQglgYVbBuJ+I5GqnzdiA2fLhaHqVk8SHRGDU64jVtV7tw3yCDWAuZpDl8AINMCuVL2j2pO8AskWTpdqurGuj4wDcSRfvS7g==,iv:LUzKnGgfmbZBZYyax+yDoU+Rhtc+k60ZnYC/MowUJQg=,tag:r21UAW4srn0AsHNItey1sA==,type:str]
sops:
    lastmodified: "2025-09-14T15:02:33Z"
    mac: ENC[AES256_GCM,data:kJzQ7VqFNS92+/vBhI4muEM5weriVPiempgci9HW4WaUxoYXzIqf42WbvgI1hiIwz3NgCQt8xpSN3AmCi74hjjU/Tjda5sPzdAQR4geD+liWStdHHTaYGAFuIDwLAm6snbxMFbcMVAH3VwaqIKP3r9AGj1TcqnL8rGTdgsf05rE=,iv:TcL1t3CfiCWupeiTQlqmVsfFXWXYpwrxRJIQGxmYzsM=,tag:BNrrMF/U/rQynJ0V8l7XzQ==,type:str]
    pgp:
        - created_at: "2025-09-14T15:02:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63AQ//Ydo+mm70mgg2Q/VMQQWeFsBO+m5/2zLYD6wXf90h3GRa
            kuKvfUmwrbR+WDWTHpHb8anTriWytj/GRu2Fd+KOaOcpdWuINn90yhkEC119oOLK
            B+e0fvd7kDNNddb94ALRpo8pKZLrsziRoweHJcL5wX6mN2eDNpXssDt0sNZFZ5Ux
            caZ6RcIZgjR5mpZaJmQvaGpV6ItWuSjGvw4cGlVZP0F6I04V4hV3MtskDJqviRoR
            Ta3GT8EorFVvRF46ijq2lgBFbT6yt+WxXAH8JFBySCocN1v6d+BDoAczdST4qukR
            RwFCNkimxQlZB7trGzjs3qeXLa1x6RAwQV/O290aAkl8Sfyuezku09Vlu1UmvGQg
            9tvSQSZtkF4QNrW0yHFh9+gMsJuuxT2dcJEkY73XkEF9nJXkOKitHHDWG0Fe1HpA
            1MQ9cSxWZag+17Bz39sxpIVRK8Bk8Rn3J3s44+1tBOZ4z7foCihlAlJEJw5AoXta
            oJxEl5T6O7fJzSIuo5Plb1GvCDhm2pPRWtOFBz079MCcQ1NdexVAnj9iW3AO8yuf
            JWX1o1LULkZl0s2kzUNMuhtYStT5FGW64uaG2u3WCyyLtK1gCNaSz5b+0Yw7ddGl
            RxSzSyTarIBYyQOjKqb1MKt69GfV7ODKGNPUkXRGbxpjf7SEvJr6vxksdSpKmQTS
            XAGbUImPCRpqzsY8jj9k6DZPwxHapCFeOQWvl8KHHrx6js13Kuws+8y41Hm1kCDr
            ulZlws94Gg7E1B272bDZaEM4g9RuvRLyuYpgNAYlV2kckFrUcNsoBtTmWzBi
            =JzdP
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
