apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: frigate-nvme-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /mnt/nvme/frigate-media