apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-path-storage

resources:
  - https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.30/deploy/local-path-storage.yaml
  - frigate-storage-class.yaml

patches:
  - target:
      kind: StorageClass
      name: local-path
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          storageclass.kubernetes.io/is-default-class: "true"
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: local-path-config