apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare

resources:
  - namespace.yaml

helmGlobals:
  chartHome: helm

helmCharts:
  - name: cloudflare-tunnel
    namespace: cloudflare
    releaseName: cloudflared
    valuesFile: values-override.yaml