apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare

# Create the namespace, config, and deployment
resources:
  - resources/namespace.yaml
  - resources/tunnel-config.yaml
  - resources/tunnel-credentials-dummy.yaml
  - resources/cloudflared-deployment.yaml
  - resources/tunnel-keepalive-cronjob.yaml

# Secrets are managed via SOPS
generators:
  - secrets-generator.yaml

patches:
  - path: patches/tolerate-control-plane.yaml
