apiVersion: ENC[AES256_GCM,data:bJM=,iv:DhC+eoi7Jcf3o0YlnVYclVKP+sppCP+8dwqvId81G6s=,tag:YiS8wngxigcfLev5WBIU0Q==,type:str]
kind: ENC[AES256_GCM,data:x/uiRJ4w,iv:k5HukCIAqpwP5my0deHWPdjQCEvjbDapcJaLH35yMd8=,tag:3065/cTmawMWr/d1uwcPaQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Zomw+Xf3w2Bly5Xku+ogC8Hj,iv:Oo7+acePkrS+L3/h+hwJzuGO7oCuSTVdEFDo0rVY70E=,tag:OvNXHYE6SfiJmMhVE9iShQ==,type:str]
    namespace: ENC[AES256_GCM,data:ciLM/xSVsg==,iv:3WQ55KIrXXAUAfbQ0Lr8y5JzS8CgkZiRRInDR16niGM=,tag:BQim3CunbDcTeh1Jb8v4cA==,type:str]
type: ENC[AES256_GCM,data:Ob7t0V6k,iv:ek3JPo35d8yX4hyc53EHa3bVFkgrZB60YKzm8oBTOwk=,tag:DQ0NhhwrHcXcRLLDAuYKzw==,type:str]
stringData:
    reolink_username: ENC[AES256_GCM,data:m9kvZoI=,iv:6Xc4FDu9TlLXPvVwCz4WW5jNJgtDoVRXV/Fa9p61rZY=,tag:OVmmaHGryqxXyf33cCPdTw==,type:str]
    reolink_password: ENC[AES256_GCM,data:0SBDuzW4MQCREQ==,iv:OTo2XZG2Mw6ezQenytD2hF4/2mzN3nnubDFryiQDXTI=,tag:HrVxF+o28t6OnVz3RkK5Zw==,type:str]
sops:
    lastmodified: "2025-10-11T00:16:28Z"
    mac: ENC[AES256_GCM,data:O3S0EGsSLTEB7JD1RM3H0jR8RS6jqqfubZisWTNwO96sc0Nwb8zUqQkqlsN2LfSte6NigIq3e/Pe2x3vS3Phg1fGOOc0SfTCyQte/ptD2e9jjYfcJNnMbj5umjukBy3nr/bVpAbn2cL4P9XYVreYeaC8lsuUZlbGNECaBIVpgxc=,iv:vaMATtmbsVMsuiHgbV99xZo9ZzPbWTmGOu8i9yyKPZA=,tag:nkbpjW+lOuthHrmU9teMCQ==,type:str]
    pgp:
        - created_at: "2025-09-14T22:25:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63AQ//W/wBJRMfMMtpKJoYq7uBdCIZORQAXS9cpC8RqXqQC+xU
            SNQuim7M83+eHc2WAZqYLSKjoH76g7gbmWfVwTXTf5aigoIaoyOtAL2S1voeDCxn
            7Du0c1iuzR6meV3aNjKExpSEBItQ1JjHLY//nQ3OS1bGszk6H6rP+ag9ZpFyOsVs
            Giyts7OCLl4IY8VnJEHSdoSXtEMhNqGZfkHrxT+5JGFmvocC/RfO2Ux73WPxaDcc
            FvPTdBYwhs66mtE5Uk13cv9/d0LT1/rLlZiaw5N4taH7SUx/kEuMtvLCXCtuLjoA
            4rYfHXAWlHPTNUeJpdM8nFNUXrm4oF3ZxdD9SLjcpi6r9LJYAPgNGTqOlKpuNJ7j
            Z0QFwTB0wCw1qK1C07TtT71wBpaWbWDeRWhKUoyEPQYVzPIhwlYXLoswNFvnlhCN
            0gh8bz8g7Go+MbwOq7H6wYr8XTKCGpW5MJxwilPP1TCV9nRIk7CGUjbq1s74ZFCY
            Fa21ZUuHYKMddaMb0PWLuRnHcu2nl/hgOm+UBvcb8HlY5te2oGNTZ4ETTX2a0y6+
            z5MLcQAVFLvLfpkfCLzSDKsOnXbTFd10c9tJjy9772Jm9y7VWLSvupM10rXn+AXq
            uqEC2O7HBBo5en4Gp/Gzq3NQ3hlRrcyua1GZghzUaaChyUAwmMDkPNaJj3PrylbS
            XAGBuPWiyxHAI3ueobpCysG+lvppjrte4J6EW+M50tQmG2fcdEKXbieFhCbftid+
            W4Owx3RbHbxQpdzBNwdjG2IU8RT0Dpw7HcoR/1waVOdGkNKB0D9ivD7iOJjo
            =ZpK7
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.11.0
