apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare

resources:
  - resources/namespace.yaml
  - resources/tunnel-config.yaml
  - resources/tunnel-credentials-dummy.yaml
  - resources/cloudflared-deployment.yaml
  - resources/tunnel-keepalive-cronjob.yaml

generators:
  - secrets-generator.yaml
