apiVersion: ENC[AES256_GCM,data:cco=,iv:aBuutzZtrqZ34QjGhBshagk+j09DI1p9mPN1B48o4Z0=,tag:ogImKlNpKste3ninwAOfrQ==,type:str]
kind: ENC[AES256_GCM,data:XUN0nNvb,iv:r25/9AgNzbEI2cLEWeZ0YiMDZ3EfjxFFqlUDoYbEhps=,tag:q3kH4acfxj2UtEVUDj+pug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WOqGQ9zTAR/1gCbqNh7JdEtZ0HG20a19VA==,iv:NqdBvAb2PZUiKIM1u2W9dTFVekWW9fqWQ2mX87+KcbY=,tag:WXdsCt1WBCVCHkRKw1gcUw==,type:str]
    namespace: ENC[AES256_GCM,data:tkax2rteMj0=,iv:giAMssj0N7p8WC78KXeciWljKfEok9niaS/kpLECnBQ=,tag:1PnxXhZwIjYXLmECtoT2tA==,type:str]
type: ENC[AES256_GCM,data:f93Adt5R,iv:LJqb2g7xNMI3e7+P778zJvdBfX5BH9hpo8NIXO/D8B8=,tag:rAIghux7opC1tYqH67XhjQ==,type:str]
stringData:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:kpUZq5kX9Gdab5zbtzxxL0LvVrA1aIoxbXfX1M0xZbgtlFRi9kypsgMCwG+0UQThWkeUYr2/UfxY08bBLgAkJE4BMfkHxdSr1uqQ6v6emPoa/CpM8eGGWWllDFCjYaRgqtw2kHe0nDNMsBMMghNkjuVzbcBT/kngRMILxgfYHh943RC7SWXM3NMwxk482xHN2XI0huH9HyQloAcbYfkJMXzIA/SRnnIJVLG2dRLsYhWUBJWbvUlOZ1pymM3HAa4wz+RFQu3SbUwd6GjVQQtlsEAfWJmZTe9fSLagJ2AqxrYdBHj4GZaV4tUUeBivjdSgxgscps38pLy9OQ9d2YgCsUuWoi0VdGtpFksGvFG2hu/MV/lPd7dgfdcmkeN3N7tBeJaf+4fMoGib+XXBqcwBrrPOoHgUi8YVoEgVsF5s1aFxiH6foWJ1XYlAjbT4gQ6RITeA/1pi/+YjWsiFizNeppFDco6IrVzNQBYMNYnMJ+rUvbmufhv342R7KOaEUOiFXIMOM3HFuSd8U4I3Me4Z7+EkC16oHyOfqdB+s31rJGaIbgZI1zxfSYPSg0QJFUCBKLQ58OhjG+afM/pq2TmBInEy/yvUZIugqekZSdhbYHiANCJXTqn6Z3tkrLrP/WZ6,iv:8QwIH/Lb75/cVamrKAzXB9yIEiXGlF2yrS0fBArmAFs=,tag:FNJNyrezPAT8UDiOv9n7Lw==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:6x1wJAqIHYVuN3eBXu6iMuw00iqD/GlUGvOVtj/U3uqjBL5R8k+YK1bNNdKpunlpxcKgugKZWTGGD6WrzU4hvqWGXIzVIguCg3Owq4AS3kJknwGZNLz3WMwXwkMDxwlfl2L4S4PFhGkR72aZuPAfx/pg3OQSJ0cgPZ85ASd8y9uF5kYRliE=,iv:hNSjdqd16HoIdeBPqS7fW2kQNTBUKFarYHbhqxlfWFk=,tag:dW4HRYzKyonmuq9dOsfsBQ==,type:str]
sops:
    lastmodified: "2025-09-14T15:03:52Z"
    mac: ENC[AES256_GCM,data:87kjDCclEX8Q5oUvQioxy7KyRMKaKiaqOHCQdfzUhdRD6t89R3Fa3EHugbCIeCr3Oref4gAANjgDqK/lSMjO+rQ07ZDS/iU8yXMStBPV7pJwQm913+hPfC8aMUlZoSlYnPesdSEpZzph9pU5ylVov9T5xl5X9wI5c4f1zSu8IRQ=,iv:5wu36bArrYftpVrsKd1xnCSM6gdGXs4R6jJROq8fAbs=,tag:A7WEFd+4D9s7t4hJ3c0OTA==,type:str]
    pgp:
        - created_at: "2025-09-14T15:03:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63ARAAhO8sN8QDRtBVW73EtXQaSgV/KTx2GJ/6HATVDzeTFitB
            KoKEDT1Y9nCDXISgQ7Bs8euV3f5cYuvzzNMZ8HvEPDrWFzS1g7JxiJtEgRiHDORc
            7ipmkNgZCqoHCDh2kLJexRHhDDEdE2iUS8a0S9x3kCQyuwUHjl9+I9gqXARCkegf
            UBfMFW5Tb1tbWwVCJFFct2q0YTYIeWahQXrTCykKtEhXAJhORggppxzzuSt43Td8
            rejMLOHc20U8v09mK3WsKiDV91AJepeu6OLSlnA4lFljWyByc/LaagROPjJAVup9
            y5/tIwzsHx4MJC1JtoujJZB8Mj1nBRvY3wqTAwUvv4dw/3hLmRJvbJmYgdVhstNZ
            CvIPQgUlMWnKjdPV5dtGK5ovLkrEomv8ORDlFU3ZkF3mCwjwW+kFpEDVPmVLaBVX
            L4tlh7Gz5oL8fReJ6mhhNZ5yxoRAou1O5HYiUIw0PT2MoymVvVe7D96eUTh7GV6r
            2kDnNDjG3ax50plq+W82JpHVCOr4GrogaSqGU1SbnaTaNBA5zNrCexFIURthkamA
            9WWj5VQ9/3dvJb+mkKZs11GY9R4v+kpQy4Igzp/Ui5TwTINWvT6TlPJGAmeWNkMf
            I9iIubVrTSUptI/F9D9v8RULIg9fNcc54o169sgkyHlzkOIUJJP6GloPsHHa0lrS
            XgFLlkaS8HIz7qggB+nqq7rR2aDZlUuI1tEHGfyM9Ei5XPlPIWLHtcEtaiHpa0Ij
            Ooq4PVKMxO3UAq79didRGWBCbdl4kjRWtGONe9YV2KT3XJmnCbTXXRE0/KCbwAI=
            =CveI
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
