apiVersion: ENC[AES256_GCM,data:H/A=,iv:psfv8Baxz986yAOzxjmyB4AchhRAxjXPQh/8AB45/kk=,tag:SpffbTD+o0cgaBFbxBZvvA==,type:str]
kind: ENC[AES256_GCM,data:GCX9gWly,iv:BRz1CyjkxPeGo75oCEFvKhJnQFF2BLsKtDHO6RyRh8k=,tag:LTG+2nTZb8iqtWVT+xwPlw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:c97zbFvZnEI9wLsGd5OwAmsvaDJ4Him9tw==,iv:qDv5kI6vjA4DXraWM4fk2ZWxJIBpstmqSDG3ZbUHtzw=,tag:dNdldrAtTc0pjsIQIWJvng==,type:str]
    namespace: ENC[AES256_GCM,data:I8qD8+6hJsE=,iv:vf0YQ86wCLBg932+Y9m6XAFG/yTwdgfhERcg8GIQac0=,tag:4fRlj+a6WY0xt8w1R8piRA==,type:str]
type: ENC[AES256_GCM,data:lxuyYA7F,iv:RvqeGoy4/KESOETQe/2NR+HPWaOEEMaZxcYk8uowo6E=,tag:35IgqqeQ6R1mPwKoubxyhQ==,type:str]
stringData:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:IfZ0iBaKo0mN0AukmeLFMQJrvjlo6bEqu0TgOseR0hRp0ygrqLM9127wtRRu/WZJvqQcJ0RCfpgGwfsvNd9k35JeJ2h4tRDaB5KN2BHndkfFeFez6yV5XqqfsTKPTrmYNSCPq06X2lfxjJPnPlIdEqK4JUWfpB99xsITaN0+b2nWtCwBxEc34mFTJsJwpKJjkwVjRQf+G/08Ciu4dHrDBwGRYxZI6zDbRsa4pdcfRwxbFBFGi+xWfond28m6NYVsZ1kHEp1Ebq4jVZALVnoEYvKzuWb4xfUhZ3vtVhH2WoLP/Y0NF2s2lRipuNll5FifY8kuAlm0qFdGZs4o53uGmP1OgkCqDNyMpgW6P5qEEgx/3NP1BpDWprOWFuzEEG1V3askJZ1EZv88gZn+QHL51+D7BZbiJnd8nRwZHvl7B05a7XifVO1l7H3bwK18LG/rqGN3l9bAPjUxPmQ80jU2e6sVSj5hFJoMYrvh/nNizLB+liDExa07HOZnBtDDE4EvufJY2dHv/+hYDgeDaHpOKltrIm09pSFyEE3Ma88iHbWMCGZotjgndHS7RSCmlmIQzW8zqYLWanaDp6PhjPiCMa0+wpI1a3P9H197QF1MCq1/hk6127JKTWY5hBCfQpwm,iv:J2DWZH58/AZlyMo7AO1kmL4lPXripZxgwjSLCFJfoSQ=,tag:JnAefFckoJ327kjEsKc75Q==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:Bf2jQ7vIXyIVFgHdzfq0aUoBzGSo7mZKYh3t7AWabI/34PH1StIYACTjakML34NWgdDJq+w4JVXATEVVwBJ0V19URcd2hejZL1CKiocQeJEjLmAWrl4dxpLyJAhFWXSF6cH/994aX+Tiitg7kZFsz2V1dk/WqzYKKHa11sE6yUsAJDrFTQI=,iv:ZpTCYVPBXkwv4KAoJPnCMisZ5J3F7tZQ9kXanCYG4Iw=,tag:W/BXdJkZA2Q81nOc+023Nw==,type:str]
sops:
    lastmodified: "2025-09-14T16:22:12Z"
    mac: ENC[AES256_GCM,data:GkTl4SkmY3UKBvpZUde0PsVNWgfjvE2Fy9JkqmdnFRKMrt8gGJ1P/Ak8p0yC4ZAzdY357N5rbiA7K7G3YlBF3UVgzjs6Q0QYD1R+wCoYji3YKZzwyHZILcEoFoaMFGinTZkUM3pycG8OgLd600pkt1aGiOIqON5qwzmEBepqkvQ=,iv:Wk1PR7J9X6vDtUm1GpF3j+zbtmAiOE/YQthpCfpi9u0=,tag:aGlkzawinLSwyu2B4BzkbA==,type:str]
    pgp:
        - created_at: "2025-09-14T16:22:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63AQ/+OTemf8fPrM0M4EsvM1Sx+4oqOFmP6HkYjjnIKA0fEoLp
            RVQWoKRp4yFN6GF2KNYq2wUulsxSGYtn+q2q+tPQWARKPXDIWbN64d2UfekPcPPR
            mrO7dhFypi1Zx0kmCTcXo7LYM/gtHHBzUPIksEa2DteuRFpTLFeUDjT0CvALo9mK
            Z/+Hp6Px3nccB0omBnNPAGtT1cLkWdNFpO/0imvmzp2gjEXhOaD5MxitRwDhaqMw
            UxRiPieGIu6V5bD9xMHNTVCYiW3C9FGEo2vQ9bZCAJjDPQAz4XCQRUa+HU9LrsnA
            7XydUDAxek/4LL4b8aYD+FtH2DNMpPYOx2yXQzwICQsSAJ3FUalGKl3yLhmwMHKt
            CKW1ROdCsF9H9KLt6e9uQyeOA//qDB/tUZ7/5TqK359U028dPUzVJq7Jz4K8406E
            VOOuyTFkPdj/zi+TwCvCdgWIfk2U83UXvc4jvjNePMVcYPuq/+IFsp8MAJJmbZTH
            mlGga9AkxxSiBISPrh/Gc2R/ZEiWMKha2FkDA9xC97VKEW2A5Wd6Y/i4w+VEOcar
            zMfrvL7emAYPGKP2GEXfMY4qyeU011XN7+o1OnzbjY9V5+g8IvJuR+wq60T5bcQB
            8874c5ORHBT0sBW3yFJ+9QT8ypBPwbvNy8cXhs4vHI9JBz0f2VplXW4Xe4x34ajS
            XgFWw7erqUp/XUBVcsWh4bPlTSy7s2Rl5u5LbifYCiZQ19R1yLxY9JOZ1741O5Iw
            JQQUtTWDmEc4aeWAULVB0tsATzLRVPX9zuddbaeYFO9tZYHFk7jjyN6HzJrwWxs=
            =4YFU
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
