apiVersion: ENC[AES256_GCM,data:kuo=,iv:EFxZQGJy/xZcjauQg3XJQlZd9b6PPFT9pA7RQSCJRDw=,tag:CX3ArIQazMGyQfaPlg61Kg==,type:str]
kind: ENC[AES256_GCM,data:xj4TPKq1,iv:+306R77JAUwWhz+4LjGqMHqMhwgUpjPWNRLHAk72jSg=,tag:Ys/dl66HAU1s8z4Br/f4SA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:m5CfsRFgUkAqgjX+,iv:/GuiiSeM6H/YRMvA4cSiqJYjh1q2e6t+Hd55iAhAcx8=,tag:R6dWtolqAaz1kvMVwBsKQg==,type:str]
    namespace: ENC[AES256_GCM,data:bXCUdckrhKEqzQ==,iv:LZI5ckMB1OZKjlRinjjwIG786R4CnjV4GXcmuSNq1eE=,tag:957kQx6ZlNXkKcyRZupt8Q==,type:str]
type: ENC[AES256_GCM,data:0HUf1ZX0,iv:OGtPiY0Hem4xTv+YfVUvkRj6zQWFEmQN7Gu4dIkVIa0=,tag:mi2Mog7Ks0nUsqNJqWly2g==,type:str]
stringData:
    token: ENC[AES256_GCM,data:wbroVSm6w9okzP+eypOJT3X3Mo9hvoYhv4dP9pndHlGBQWtLEWJdlG60bgkh9czak/w0HLCDwRG6N7/xu91o66bNhYSJnrYB/meIzLt35T8Iyjpm0reD0Md2G1fwcXUgpskC0Jz0u1OXd9KebxlTkm4eV/ROsanu8Zgaapx9T9zbELD14AoyCZgMN13Sc1KY/sjVHUgHIaKOqUJhPgdPZaEGFQFaMosQU6cir8RfYrlB74duBnLjOQ==,iv:kuTbVCOlNWz0maNZo75vyZ2i91Dwk1Q34Ab0kIOLsWo=,tag:rDgEKcuxddNo5yN6QeBfzA==,type:str]
sops:
    lastmodified: "2025-09-18T01:41:36Z"
    mac: ENC[AES256_GCM,data:lwVYcS8l+jMBMP6cLtRH0gaRUnjnXccrFrPewxF4qFHkJlKhzpUyKrGZ5HarYO4R2mM9fzuGvD+DMxOXZ5lTiy7JtFIx+5pcTSolya4jMcWPeBwMNZZIoOVz6CKy2nMow/p2y3IMyYp7JHBhgyIdq1natslyscFcRQ5qzev7xzQ=,iv:dC25RcMWS74uGxlsnxRtFM75YX57LSUik1uI770dq4g=,tag:QfgtkqZX2NDt+1eGPQ/jxg==,type:str]
    pgp:
        - created_at: "2025-09-18T01:41:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63AQ//aHqr5hkKJaSKhD0P/DSEmg9bCs0KvSI8JyBeqyD9SfXH
            fuQhaUPsOQC34epUm3l4RhMBmUrlUURc/86mUfioGf8/Jno76yylXPsSVY2ELgPX
            zCT80CKDqWJoSEH+XgsIc4JmrXQDZZ8+n2roaN2SoxZmmewjPp9i4m3HA6/VAJmN
            YRA6JGkCqH702V1qtDNuwAt8jb6b1hc/S831prfsjysCAfEgg5QyNfLZS74TBVXs
            gXNn8albFV8jfN3ugxfmNWW8+x5mT1xNO1AKS0dcyFgjhRYs88d2mEJK7IrZ0xoX
            xo7Fh+vr2GpONrF/zfYAo2mT8nCeP65mQkeIYFOozzMqsBvOGk5jHGg9P6dgdbLa
            hTVOZZae6h1GgpyMVy1Jl1c9i4YtI7nWusN115usikxRPzW4v6I+jK6y/AEKaiBp
            i3pywIsRaJ3mH8GAFjERXJi60e2l0fIs9wa6d79a/sSdJJxifc+5b3OwVNfWBQ6U
            ocnLb+Jt7dckYAxWGRMu1xy7h1LXVFFjoAs2VgaQN1mYMk8NpoXTa/0oMrYT5HHf
            14i9VTeQScuoxvyg7WExI2us5sh7H2h7CMEkzT3gTuz3X3M81zYFLvuKX0oK/SI8
            0NlmFQ4xuAbcF52fDADbyzA/nIEsQznw3FZJGHfgi5sahX97HpJhAZnjBFkbLenS
            XgFLFASGGVQx/Oqff7KaX9++quN1TA3lPw3zSJZyVp++rqicZi1DrEt14hO1b3L1
            A8ESOiYWwr1hd2birYS9Xcw1Z0EnQTJj49gI3nHZFU/BM2CGWP+oaIY9c2T3gyo=
            =0TbF
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
