apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: frigate-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secrets/frigate-users-config-unused.enc.yaml