apiVersion: ENC[AES256_GCM,data:giM=,iv:gkwnDOd+BcATA6ggoOHBbP/eBZSr+8+4yT6K37WcFE0=,tag:Hf8GPK57ivN7xWagvHVRSQ==,type:str]
kind: ENC[AES256_GCM,data:zxyM4UI0,iv:Ta4Lv7LUPBXtYRJ08qL7n054g2bwTMr4LLRVV/jnETI=,tag:ZqjGnNT1bIm0t3rVcPzdmA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ayvZFL+5j8d+JhH2,iv:zlOsOr7ZEJL24Y6jqYQXdkgSarlGkDgQ70W7leQURPM=,tag:INzbagZZv4JyWAjYnmd34A==,type:str]
    namespace: ENC[AES256_GCM,data:iumBrQNAeQ==,iv:vLYFLkiLppqwCwCw0FuFWuT+rE5bRPaII16TxVqU4Hc=,tag:L6Jd+U2lFXVQeev5klApSA==,type:str]
type: ENC[AES256_GCM,data:IiB4Rdm5,iv:coJtGv+TxGfshME3QyJpreyAg5JK/+iy927RtNtZTMg=,tag:9bJIGhU/XNFwqPphYl3PNg==,type:str]
stringData:
    auth.yml: ENC[AES256_GCM,data:HhuoHMagNJcjf8okuqyOPeiSqi37sWaMPpZQUvjmC+BqlzjukDfHraYSzCPO0LvV7wJv+n4aw9VXgBuKJAWdUkgLu3nRkAYXSfzvFg==,iv:Wvs+zbXcyu+X9vMNNuXQEn1VGBHyZZYfLf6BB4gnd20=,tag:iJYBc0nWO0Jkvn8leT46Ww==,type:str]
sops:
    lastmodified: "2025-09-14T14:49:47Z"
    mac: ENC[AES256_GCM,data:FVu7PUtgclW+q/f8u1y+PSa8ioJkbK9D787mh4GobahZcQvRmBq54O+kw7Kco3u1L30ohExb7tpV6V0FMe1A03c+50V90E27ojQpGaAoP6/XhcK8YsjIEZ6xNU8O9EHi4mXccRafVBzn1xKBGYPBZnWyr9+API8IKQbfgh65EgA=,iv:EuU/+9IN4PdHgLF8uhVIDuRjTyvuG27DMHE6ehB4huw=,tag:4v044A76LSPWfEOrs5RXIA==,type:str]
    pgp:
        - created_at: "2025-09-14T14:49:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63ARAAqQ12BJKMjz/GJtbA9nrVAv88ym1EfTF5fOxQYMaajgoF
            bARc5mva22aBDVXdmtAjvn546/ldc+u3q12DN6Lfkee/qd2KokamteI2geYwWOFF
            yfx5EHRXzqGJGTv2LRGc9Wx8Jt5CUCF9aTGjZVkriQVPNgx/s88Q6StUFLQZGqj6
            LrKbqx58M46R/i2eY20/vqtiw+Obne/5NYKycFZPGJfYEJoJ1qJFk3iyj4PEr47S
            dOvgO1PSXCWzTVXNY7UrnnBsKUMP8c8i+lpcx7kQGIvffb9zh13I3x0CeincVmsd
            /V9Cn7vBuu9ET4y/S4bionajMp1oTdRt9h/KZGAT9KiX31p0zEhIgb/u26Ocb7Gi
            SnyKm2NYEQ4t8G3cYaQChRF/FYB1ngO4hUA6zI9K3bk9iPFefNnkLd0enSTGPVn4
            8B/DbuIMlBjI46kjq6SYAlnbY0X597q4WqKsKM7yB75j7ya9taU3SDo5K0SXnASF
            WRMN803qHGh27Gb1iyfzIWU/aPHFCUmLwI6aTP24KcCE7xoX/ON3B0y/O9J/vthk
            D2rR5L73uGB9GQNIh5PkPp4ilV1tOBq9XK1Lj5pb3NwRATyNkR36DIsOX63K24iK
            JY8yNNvsdcAFLx/51+qdZGVSYta4JlIHy8I3VU5QyhOQGN8Z55j2gVrC4mFsP2fS
            XgEyy/Oak8jOM75q4FmQlmFyfCom08un3nqLnZcLqFTLely0VI5vtDH1IH2i5dhK
            JqvVQYB0zBrW6Gl8deF5qG78A9y8+kRrMqoeKQ6JGZAY1wGZyYlrAAUC6grwQXc=
            =hYjt
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
